#!usr/bin/ruby

fastlane_version '2.0'

default_platform :ios

platform :ios do

  desc 'Bootstrap dependencies for development'
  lane :bootstrap do
    bootstrap_carthage
    match(
      type: 'development',
      readonly: true,
      username: '',
    )
    sh 'brew tap yonaskolb/Mint https://github.com/yonaskolb/Mint.git'
    sh 'brew install mint'
  end

	desc 'Perform test checks'
	lane :test do
		bootstrap_carthage
		scan(
      scheme: 'hasbro',
			clean: true,
			formatter: 'xcpretty-json-formatter'
		)
		danger
	end

	desc 'Deploy a build for beta testing'
	lane :internal do
		match(type: 'appstore')

		bootstrap_carthage

		add_badge(
      dark: true,
      glob: '/templateProject/**/*.appiconset/*.{png, PNG}'
    )

		build_number = ENV['BITRISE_BUILD_NUMBER']
		increment_build_number(
			build_number: build_number
		)

		gym(
			export_method: 'app-store',
			configuration: 'Internal'
		)

		pilot(
			beta_app_description: 'Build for an internal testing purpose',
			skip_waiting_for_build_processing: true,
			skip_submission: true
		)
	end

	desc 'Deploy a release build'
	lane :release do
		match(type: 'appstore')

		bootstrap_carthage

		build_number = ENV['BITRISE_BUILD_NUMBER']
		increment_build_number(
			build_number: build_number
		)

		gym(
			export_method: 'app-store',
			configuration: 'Release',
		)

		pilot(
			distribute_external: true,
			beta_app_feedback_email: 'headsandhands3@gmail.com',
			beta_app_description: 'Release build for testing',
			wait_for_uploaded_build: true,
			changelog: 'Release',
			groups: 'Client'
		)
	end

	lane :bootstrap_carthage do
		carthage(
			platform: 'iOS',
			cache_builds: true,
			use_binaries: false,
		)
	end
end
